# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ed2dabb62de9d673897c816651b8024ea6d336529672ab74ac91979c4fdd600eff4dce812f6ba0ac95ace6c948ed4fe067406a24da4533b9a5b173dd8b4262d

test:
  secret_key_base: c252a76f16f8fe833c5dda90a1a8a9a401ce95bda029a8870240b7068e79589ed9a6615f84802453e2b41f1dbd09a348f10f89259b1901c6072201cf377c09d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
